### ISSUE TITLE
Error from tile-converter: TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Radik24** [visgl/loaders.gl#1734]
Hi,

I'm trying to convert one large tileset, but tile-coverter throws an error:

![image](https://user-images.githubusercontent.com/23722745/128046664-af83b37f-888a-4991-ac90-ab8a56bf3ddb.png)

Not sure what is wrong, but I can display original Cesium 3D tile in deck.gl.

I tried it with another tileset (smaller part of ^^ large tileset) and it was successful.

Also new I3S is vertically misplaced against original Cesium 3D tile. (upper is cesium)

![image](https://user-images.githubusercontent.com/23722745/128047313-c0efa3b6-7d02-4596-88ef-0b61a0d9a9b4.png)

Command: `npx tile-converter --input-type 3dtiles --tileset /home/app/temp/ed0ac141-92e6-4ae6-8ed6-9f2c9cf5d971/old/tileset.json --output /home/app/temp/ed0ac141-92e6-4ae6-8ed6-9f2c9cf5d971 --name new`

Don't you know what is wrong with elevation?

Thanks

**Comment by belom88** [comment]
Hello @Radik24 . Sorry for the delay. Do you still have issue with `id` property.
Converted tileset can be floating because base map is on the 0 elevation. We added TerrainLayer in I3S example in 3.1 version.

**Comment by Radik24** [comment]
Hello @belom88 . Thanks for your answer. I need to test it again. I did not try it since I opened this issue. I'll let you know.

**Comment by Radik24** [comment]
Hello @belom88, sorry for my delay now :) I can't see issue with `id` anymore. But altitude is still shifted. Should it use altitude from original cesium 3D tiles?

![image](https://user-images.githubusercontent.com/23722745/152803172-e28d7f60-47ca-42f0-af52-2205606eeb0e.png)

Upper data are cesium, below converted i3s. I switched to latest alpha release to create ^^ data. Thanks

**Comment by belom88** [comment]
We convert the elevation because of different height models in I3S (ellipsoid vs geoid). Do you check the resulting dataset on ArcGIS or on loaders.gl? loaders.gl doesn't support geoid height model that is usually used by ESRI.
The difference between ellipsoid and geoid elevation can be significant. That depends on coordinates.
Another possible cause is terrain elevation. We use TerrainLayer on loaders.gl as additional custom layer for such cases:
https://loaders.gl/examples/i3s
![image](https://user-images.githubusercontent.com/18549629/152807519-3d62b887-b0d8-4107-9e6b-920c6d0809e3.png)
