### ISSUE TITLE
maximumScreenSpaceError for 3d tiles

### ISSUE THREAD

**Issue by yan-map** [visgl/loaders.gl#1747]
Hi
I didn't find any way to override tileset `geometricError`, which is crusial for improving rendering quality

There is a variable in Cesium JS "maximumScreenSpaceError" which overrides tileset values, so how can I increase this value? Thank you

**Comment by belom88** [comment]
There is an option in `Tileset3D' `maximumScreenSpaceError'. I'm checking it.

**Comment by belom88** [comment]
There is an issue in interaction between deck.gl and loaders.gl.
deck.gl has `loadOptions` prop. It is the only interface to pass options to `Tileset3D` class. So it contains all options user intends to pass to the `Tileset3D`, not only options for loaders.
But `Tileset3D` has its own prop `loadOptions` which is used only to pass to loaders (I3SLoader or 3DTilesLoader).
Due to this tangle `deck.gl` passes its `loadOptions` to tileset's `loadOptions`:
https://github.com/visgl/deck.gl/blob/92e18f20bf27d1cf43bead488411012314588fd9/modules/geo-layers/src/tile-3d-layer/tile-3d-layer.js#L120
So `maximumScreenSpaceError` is in `loadOptions` now and `Tileset3D` don't see it.

**Comment by ibgreen** [comment]
Related to https://github.com/visgl/deck.gl/issues/6074

The `3DTileLayer` works a bit differently from other layers. It offers a `loadOptions` props like all other layers, but it doesn't pass this to a `load` call. Instead it creates a `Tileset3D` class and forwards the `loadOptions` object. But it doesn't provide a way to specify other options. This requires some thought.

@yan-map As a workaround, is it possible to specify this in a callback, something like?

```typescript
  new Tile3DLayer({
    onTileLoad: tile => tile.tileset.setProps({maximumScreenSpaceError: ...})
  });
```

**Comment by yan-map** [comment]
This worked, thank you!

> Related to [visgl/deck.gl#6074](https://github.com/visgl/deck.gl/issues/6074)
> 
> The `3DTileLayer` works a bit differently from other layers. It offers a `loadOptions` props like all other layers, but it doesn't pass this to a `load` call. Instead it creates a `Tileset3D` class and forwards the `loadOptions` object. But it doesn't provide a way to specify other options. This requires some thought.
> 
> @yan-map As a workaround, is it possible to specify this in a callback, something like?
> 
> ```ts
>   new Tile3DLayer({
>     onTileLoad: tile => tile.tileset.setProps({maximumScreenSpaceError: ...})
>   });
> ```

**Comment by akre54** [comment]
As a bit of follow-up, I was struggling with the tiles unloading while programmatically rendering. Just as a note, `maximumMemoryUsage` can't be set via `setProps`, it has to be mutated directly on the `tileset` object:

```js
onTilesetLoad: tileset => {
  tileset.maximumMemoryUsage = Math.pow(2, 20);
  tileset.setProps({
    maximumScreenSpaceError: 0,
    maximumMemoryUsage: Math.pow(2, 20),
  })
},
```

See https://observablehq.com/@akre54/deck-cesium-hubble

**Comment by belom88** [comment]
Thanks for reporting
