### ISSUE TITLE
I3SLoader missing headers

### ISSUE THREAD

**Issue by Radik24** [visgl/loaders.gl#2049]
Hello,

I found out I3SLoader does not use `fetch`.`headers` when loading `root` tile

```
loadOptions: {
  i3s: {
    coordinateSystem: COORDINATE_SYSTEM.LNGLAT_OFFSETS
  },
  fetch: {
    headers: this.requestHeaders(),
    signal: this.abortSignal
  }
}

```

First request:
![Screenshot 2022-01-07 at 15 42 48](https://user-images.githubusercontent.com/23722745/148564511-08370800-2b0d-4434-abda-894aaaf34f0c.png)

Root tile:
![Screenshot 2022-01-07 at 15 44 25](https://user-images.githubusercontent.com/23722745/148564563-6a01f5b9-2f8e-4e38-a791-9bab044f9d14.png)

Another tile:
![Screenshot 2022-01-07 at 16 19 28](https://user-images.githubusercontent.com/23722745/148565002-7cd53831-c82d-4d95-8bde-4856a5af239c.png)

Do you know why it's happening? Thanks

**Comment by dryabinin-actionengine** [comment]
@Radik24 Hello!
When we load I3S data we only expect a token in root url and we don't use any additional headers. I guess this is because previously we haven't use the other way to load I3S data.

`const rootNodeUrl = getUrlWithToken(`${tileset.url}/nodes/root`, options.i3s?.token);`
Actually I think we are able to just add fetch option to root node request.

**Comment by belom88** [comment]
root node is only loaded for 1.6 datasets in the special place:
https://github.com/visgl/loaders.gl/blob/6465d910e88fc902ebcf73b3bce4fccf23ffb174/modules/i3s/src/lib/parsers/parse-i3s.ts#L87

I suggest we can pass options from the input:
```
const rootNodeUrl = getUrlWithToken(`${tileset.url}/nodes/root`, options.i3s?.token);
    // eslint-disable-next-line no-use-before-define
    tileset.root = await load(rootNodeUrl, tileset.loader, {
     ...options,
      i3s: {
        ...options.i3s,
        loadContent: false, isTileHeader: true, isTileset: false}
    });
```

**Comment by Radik24** [comment]
Thanks!

**Comment by dryabinin-actionengine** [comment]
@Radik24 New loaders.gl v.3.1.5 has been published with this fix.

**Comment by Radik24** [comment]
Hi @dryabinin-actionengine I'm still experiencing some issues. Requests for `texture` are without headers with loaders `3.1.8` and deck 8.7.8`

It really seems that only `texture` requests are without headers.

![image](https://user-images.githubusercontent.com/23722745/164909643-6be7d755-5627-4409-a703-99a5aae94ade.png)

![image](https://user-images.githubusercontent.com/23722745/164909654-5d511db0-3b4e-40c3-a066-ef22273856f4.png)

Thanks!

**Comment by belom88** [comment]
@Radik24 please raise a new issue. It is hard to handle all in one thread.

**Comment by ibgreen** [comment]
Just a thought - if textures are loaded as `image` instead of `imagebitmap` they may not go through the standard `load` functions and headers will not be supported.

Perhaps possible to check if you are hitting this path:
https://github.com/visgl/loaders.gl/blob/master/modules/images/src/lib/parsers/parse-to-image.ts#L28

**Comment by Radik24** [comment]
Thanks, @belom88 I'll create a new issue. @ibgreen I added breakpoint to ^^ method and it seems it uses something else for loading textures.
