### ISSUE TITLE
Tile converter failed from i3s 1.8 scene server to 3D Tile

### ISSUE THREAD

**Issue by tom62291** [visgl/loaders.gl#2092]
Hi , I found the tile converter is failed when converting from i3s 1.8 scene server to 3D tiles.

Any timeline to make the converter support reading i3s 1.8?

**Comment by belom88** [comment]
1.8 is supported. Please, share more details about this error.

**Comment by tom62291** [comment]
![image](https://user-images.githubusercontent.com/8196925/155643825-264d2186-3d7d-4f66-b48b-0cb03d991778.png)

Hello, please find me error screen above. 
By copying the URL link "http://xxxx/SceneServer/layers/0/nodes/164/attributes/f_1/0", I can download the attribute file as enclosed below:

[0.zip](https://github.com/visgl/loaders.gl/files/8138059/0.zip)

**Comment by tom62291** [comment]
The Second error is about after added egm file.

I tried the same command this time (also pointed to a i3s 1.8 scene server) but added egm file as below:
'''
npx tile-converter --input-type I3S --tileset http://xxxxxx/SceneServer/layers/0 --name .\Building_11NE17D_4326 --egm .\egm96-15\geoids\egm96-15.pgm
'''
The screen has this error
![image](https://user-images.githubusercontent.com/8196925/155655201-ee5b227a-f40a-428c-9735-e033b3da0d97.png)

When I point to a I3S 1.7 version Scene server, the command can run successfully.

**Comment by belom88** [comment]
First error: seems like network unstable. I have this issue too from time to time. It is not stable to reproduce and rather depends on internet bandwidth. It hardly depends on 1.8 version of the layer;
Second error: possibly, it is sequence of the first error (if the tile content loading had failed just before this error). Apparently it happens because the tile has `contentUrl` but content hasn't been loaded and is null.

To give you more details we need the data to debug.

**Comment by tom62291** [comment]
Hello, yes, but it is private date, can we share the link to you in private?

**Comment by belom88** [comment]
You can email me victor.belomestnov@actionengine.com

**Comment by belom88** [comment]
@tom62291 I didn't get any data. I close this issue due to inactivity.
