### ISSUE TITLE
The loaded 3Dtile has no texture

### ISSUE THREAD

**Issue by yinminhe** [visgl/loaders.gl#2238]
The loaded 3Dtile has no texture
https://codesandbox.io/s/thirsty-fermi-uedux3?file=/src/App.vue

![image](https://user-images.githubusercontent.com/37259849/186804918-a76ce5bc-d540-42e0-b597-e37b36b1bd4a.png)

Looks like there's a file parsing problem
![image](https://user-images.githubusercontent.com/37259849/186804959-8f944270-bede-45e9-bb31-d601d1262ade.png)
![image](https://user-images.githubusercontent.com/37259849/186804975-d67164ac-27e5-4606-8e4b-5a2b1006a2f3.png)

**Comment by dryabinin-actionengine** [comment]
@yinminhe Good Day!
Actually I checked all data which you share.
As for `http://cim.cityfun.com.cn/3dts/x1/qxsy/t1/tileset.json` tileset works and loaded good!
![image](https://user-images.githubusercontent.com/70207219/189864588-7821d9f4-9536-4b78-a21d-c3f3513dba13.png)
As for your tileset which you actually trying to visualize there are 2 issues:

1. You dataset is not full, It can be detected by open data in `codesandbox`, In main tileset.json you can see urls of child tiles which are not existed in you data for example there is no `Tile_+003_+002` folder.
![image](https://user-images.githubusercontent.com/70207219/189868187-bf06da10-1477-49db-b4cb-8380abb46432.png) 
So on the screen you can see only existing tiles which are loaded succesfully. 

2. `3DTilesLoader` works good with 2.0 version of gLTF data. In you b3dm files gLTF data has no version and `3DTilesLoader` tries to convert it to 2.0 version. You can see warnings in console about that. But during conversion we don't handle `diffuseTex` property. I will fix that.  As for weird loading of `data:,` it is because image object in gLTF has `uri: 'data,'` and of course gLTF loader tries to load such images by this uri.

P.S After my fix should be like this:
![image](https://user-images.githubusercontent.com/70207219/189917989-e759712d-78c6-44a3-8212-c89b27653b8e.png)

**Comment by dryabinin-actionengine** [comment]
@yinminhe We'v published a new v3.3.0-alpha.4 version of loaders with fix. Please check it.
