### ISSUE TITLE
A 3D tile failed to load: undefined The source image cannot be decoded.

### ISSUE THREAD

**Issue by limzgiser** [visgl/loaders.gl#709]

**Comment by ibgreen** [comment]
@limzgiser Not sure how to help you based on this information. 

I can say that this error is typically generated by the browser when it cannot parse an image. So, the tile might refer to, or contain, an incorrectly formatted image, or possibly something goes wrong when extracting an embedded image. 

Any chance you can pinpoint and share the tile in question (e.g. by looking into the network tab in your browser's debug tools)? If we can reproduce the bug then we have a good chance of doing something about it.

**Comment by 2226174644** [comment]
I faced the problem recently,the console log is--
![image](https://user-images.githubusercontent.com/51537408/143843045-19a2411b-59a9-450e-ba6b-074146a129f8.png)
And network tab is ok.
![image](https://user-images.githubusercontent.com/51537408/143843902-9b9bb6d0-59c1-4e2c-8bb3-3a9ea77bc209.png)

When I change the option: loadersGlGltf :false ,the log is
![image](https://user-images.githubusercontent.com/51537408/143844107-8daa99d7-7eaa-44de-935e-dfdff56a02ab.png)
just like title.

Hoping for your help.

**Comment by ibgreen** [comment]
Looks like you are using a browser that does not support `createImageBitmap`, perhaps Safari (especially before v15)? 

> When I change the option: loadersGlGltf :false from Loader3DTiles based on loaders.gl

I assume the above is a typo, should be something like 
```
load(url, ..., {
  ['3d-tiles']: {
    loadGltf: false
  }
})
```

@limzgiser  Can you test some B3DM examples using https://loaders.gl/examples/3d-tiles? The default example is a point cloud but there are B3DM examples in the drop down. If these work it may be your code.

@dryabinin-actionengine FWIW, I believe we had a somewhat similar bug in I3S with worker loading, perhaps worth checking if something similar is happening here?

**Comment by dryabinin-actionengine** [comment]
Will take a look. Looks really similar.

**Comment by 2226174644** [comment]
Thanks for your reply.
I have tried **createImageBitmap** in other place, it worked.
Because I mainly use Loader3DTiles based on loaders.gl to load 3DTiles ,Loader3DTiles and loaders.gl both log the error.
![image](https://user-images.githubusercontent.com/51537408/144038980-1cd4ddcf-8405-4987-bc3d-5e7625038730.png)
After a day of testing，I think the problem is in Loader3DTiles where blob is invalid. And I also have Submitted questions to them.
![image](https://user-images.githubusercontent.com/51537408/144039697-5c946af8-edbc-44a2-a0b9-bf98306d10da.png)
[https://github.com/nytimes/three-loader-3dtiles/issues/11](url)

**Comment by ibgreen** [comment]
@Avnerus
