### ISSUE TITLE
mimeTypes or mimeType

### ISSUE THREAD

**Issue by JscLee** [visgl/loaders.gl#783]
Hi,

I'm seeing mixed use of `mimeTypes` and `mimeType` for the loader properties. 

For loaders, I'm seeing mostly `mimeType` except for video. Whereas in select-loader.js, `mimeTypes` is used. (https://github.com/visgl/loaders.gl/blob/master/modules/core/src/lib/api/select-loader.js#L76-L83) 

Not sure if this is intentionally or it's an issue. But basically it fails a case of mine where the ply loader is supposed to be chosen for a temporary url created from a blob.

**Comment by ibgreen** [comment]
@JscLee Thanks for reporting. Yes this is a bug. 

- The good news is that I just posted a PR that fixes this for loaders.gl 2.2 which should be out sometime next week.
- The bad news is that this PR may not be easy to backport to 2.1 so you'll need to wait a week for it.
- That said it would be possible to skip the typescript changes and just apply the mimeTypes field renaming to 2.1-release branch (if someone really wanted to do that).

**Comment by JscLee** [comment]
Thanks for fixing @ibgreen ! It seems in ply-loader octet-stream isn't supported. Is there specific reason for that? I tested locally with binary ply file it actually works fine.

**Comment by ibgreen** [comment]
@JscLee You are correct, binary PLY is supported by the parser, so it makes sense to add that MIME type. 

You are welcome to open a  small PR and add that mime type if you'd like, and I'll land it asap. Or just file a new issue and we'll get to it eventually.

Note that it can be hard select a loader based on generic MIME types like octet-stream since multiple loaders can easily support it. It depends on which loaders you have in your loader mix.

Ideally I think we should support some extended `...+vnd.ply` style MIME types but I haven't had time to research what they should be, if you have any helpful references here let me know.

**Comment by JscLee** [comment]
@ibgreen  hi, I created the pr here: https://github.com/visgl/loaders.gl/pull/793
so far this works fine for me since I interact with pointcloud layer from deck.gl, and this loader is the only one I register. unfortunately I don't have much knowledge of the vendor specific mimetype.

**Comment by ibgreen** [comment]
Many thanks and yes, if you only have a few loaders it will certainly work. 

Perhaps we could use the [unregistered tree](https://en.wikipedia.org/wiki/Media_type#Unregistered_tree) and support `application/x.ply` etc for formats that lack a registered mime type.

**Comment by ibgreen** [comment]
@JscLee  Now you will also be able to specify the non-standard `application/x.ply` type, in case you need to add more loaders. 

All loaders support this scheme.

**Comment by JscLee** [comment]
This is very helpful. Thank you :)
