### ISSUE TITLE
MVT Module External Dependency

### ISSUE THREAD

**Issue by downset13** [visgl/loaders.gl#981]
Hi folks, wanted to point out that the MVT module has a hardcoded external dependency for the workerUrl, making it impossible to use in offline mode or an air-gapped environment.

```
/** @type {WorkerLoaderObject} */
export const MVTWorkerLoader = {
  id: 'mvt',
  name: 'Mapbox Vector Tile',
  version: VERSION,
  extensions: ['mvt'],
  mimeTypes: ['application/x-protobuf'],
  category: 'geometry',
  options: {
    mvt: {
      coordinates: 'local',
      layerProperty: 'layerName',
      layers: null,
      tileIndex: null,
      _format: 'geojson',
      workerUrl: `https://unpkg.com/@loaders.gl/mvt@${VERSION}/dist/mvt-loader.worker.js`
    }
  }
};
```

**Comment by ibgreen** [comment]
You can set `parse(..., {worker: false})` option to use the bundled loader instead of the worker script. 

That makes the loader run on the main-thread. If that is not OK, there should also be some support for specifying a local worker (you'd need to copy it into your environment), I don't have the details fresh but some of the test cases in loaders.gl specify worker bundles, you may be able to poke around and see how it is done.

**Comment by kylebarron** [comment]
You can set `mvt.workerUrl` to load from anywhere you want. Like in the tests:
https://github.com/visgl/loaders.gl/blob/8e67b9e2147bc6a36a0debcaa34d2809cfd20311/modules/mvt/test/mvt-loader.spec.js#L20-L24

**Comment by downset13** [comment]
Thank you! We're currently using loaders.gl exclusively through Deck.  Sounds like we'll need to extend the TileLayer and write our own MVTLayer that supports loader props... or am I missing a simpler solution?

**Comment by ibgreen** [comment]
deck.gl layers have a `loadOptions` prop that is passed to loaders.gl. 

But I was only able to find it mentioned in the upgrade guide (@Pessimistress)

https://deck.gl/docs/upgrade-guide#upgrading-from-deckgl-v81-to-v82

**Comment by ibgreen** [comment]
@vdunaev Can you file an issue on deck.gl to document `loadOptions` and assign to the team, then close this issue?
